version: "3.7"
services: 
  back-end: 
    build: ../shopping-list-java
    image: imallinson/project-back-end
    container_name: back-end
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  front-end: 
    build: ../shopping-list-reactjs
    image: imallinson/project-front-end
    container_name: front_end
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  jenkins: 
    image: bobcrutchley/jenkins
    container_name: jenkins
    ports: 
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./jenkins/jobs:/var/jenkins_home/jobs:Z"
  nginx:
    build: .
    image: imallinson/nginx
    container_name: nginx
    depends_on: 
      - back-end
      - front-end    
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/letsencrypt/:/etc/letsencrypt/"
